export const Direction = {
    Up: { x: 0, y: 1 },
    UpRight: { x: 1, y: 1 },
    Right: { x: 1, y: 0 },
    DownRight: { x: 1, y: -1 },
    Down: { x: 0, y: -1 },
    DownLeft: { x: -1, y: -1 },
    Left: { x: -1, y: 0 },
    UpLeft: { x: -1, y: 1 },
    UpUpRight: { x: 1, y: 2 },
    UpRightRight: { x: 2, y: 1 },
    DownRightRight: { x: 2, y: -1 },
    DownDownRight: { x: 1, y: -2 },
    DownDownLeft: { x: -1, y: -2 },
    DownLeftLeft: { x: -2, y: -1 },
    UpLeftLeft: { x: -2, y: 1 },
    UpUpLeft: { x: -1, y: 2 },
};
